// <auto-generated />
using System;
using Dedalo.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dedalo.Infra.Migrations
{
    [DbContext(typeof(DedaloContext))]
    [Migration("20260329115115_AddUniqueIndexCustomDomain")]
    partial class AddUniqueIndexCustomDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dedalo.Infra.Context.Content", b =>
                {
                    b.Property<long>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("content_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ContentId"));

                    b.Property<string>("ContentSlug")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("content_slug");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("ContentValue")
                        .HasColumnType("text")
                        .HasColumnName("content_value");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("index");

                    b.Property<long>("PageId")
                        .HasColumnType("bigint")
                        .HasColumnName("page_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("WebsiteId")
                        .HasColumnType("bigint")
                        .HasColumnName("website_id");

                    b.HasKey("ContentId")
                        .HasName("dedalo_contents_pkey");

                    b.HasIndex("PageId");

                    b.HasIndex("WebsiteId");

                    b.ToTable("dedalo_contents", (string)null);
                });

            modelBuilder.Entity("Dedalo.Infra.Context.Menu", b =>
                {
                    b.Property<long>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("menu_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MenuId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_link");

                    b.Property<int>("LinkType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("link_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("name");

                    b.Property<long?>("PageId")
                        .HasColumnType("bigint")
                        .HasColumnName("page_id");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("WebsiteId")
                        .HasColumnType("bigint")
                        .HasColumnName("website_id");

                    b.HasKey("MenuId")
                        .HasName("dedalo_menus_pkey");

                    b.HasIndex("PageId");

                    b.HasIndex("ParentId");

                    b.HasIndex("WebsiteId");

                    b.ToTable("dedalo_menus", (string)null);
                });

            modelBuilder.Entity("Dedalo.Infra.Context.Page", b =>
                {
                    b.Property<long>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("page_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PageId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("name");

                    b.Property<string>("PageSlug")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("page_slug");

                    b.Property<string>("TemplatePageSlug")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("template_page_slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("WebsiteId")
                        .HasColumnType("bigint")
                        .HasColumnName("website_id");

                    b.HasKey("PageId")
                        .HasName("dedalo_pages_pkey");

                    b.HasIndex("WebsiteId");

                    b.ToTable("dedalo_pages", (string)null);
                });

            modelBuilder.Entity("Dedalo.Infra.Context.Website", b =>
                {
                    b.Property<long>("WebsiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("website_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("WebsiteId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomDomain")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("custom_domain");

                    b.Property<int>("DomainType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("domain_type");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<string>("TemplateSlug")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("template_slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("WebsiteSlug")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("website_slug");

                    b.HasKey("WebsiteId")
                        .HasName("dedalo_websites_pkey");

                    b.HasIndex("CustomDomain")
                        .IsUnique()
                        .HasDatabaseName("ix_dedalo_websites_custom_domain")
                        .HasFilter("custom_domain IS NOT NULL AND custom_domain <> ''");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_dedalo_websites_user_id");

                    b.HasIndex("WebsiteSlug")
                        .IsUnique()
                        .HasDatabaseName("ix_dedalo_websites_slug");

                    b.ToTable("dedalo_websites", (string)null);
                });

            modelBuilder.Entity("Dedalo.Infra.Context.Content", b =>
                {
                    b.HasOne("Dedalo.Infra.Context.Page", "Page")
                        .WithMany("Contents")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dedalo_content_page");

                    b.HasOne("Dedalo.Infra.Context.Website", "Website")
                        .WithMany("Contents")
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dedalo_content_website");

                    b.Navigation("Page");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("Dedalo.Infra.Context.Menu", b =>
                {
                    b.HasOne("Dedalo.Infra.Context.Page", "Page")
                        .WithMany("Menus")
                        .HasForeignKey("PageId")
                        .HasConstraintName("fk_dedalo_menu_page");

                    b.HasOne("Dedalo.Infra.Context.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_dedalo_menu_parent");

                    b.HasOne("Dedalo.Infra.Context.Website", "Website")
                        .WithMany("Menus")
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dedalo_menu_website");

                    b.Navigation("Page");

                    b.Navigation("Parent");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("Dedalo.Infra.Context.Page", b =>
                {
                    b.HasOne("Dedalo.Infra.Context.Website", "Website")
                        .WithMany("Pages")
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dedalo_page_website");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("Dedalo.Infra.Context.Menu", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Dedalo.Infra.Context.Page", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("Menus");
                });

            modelBuilder.Entity("Dedalo.Infra.Context.Website", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("Menus");

                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
